User.create!(name: "matt", email: "matt@email.com", password: "password")
User.create!(name: "miranda", email: "miranda@email.com", password: "password")

Neighborhood.create!(name: "Logan Square")
Neighborhood.create!(name: "Wicker Park")

Bar.create!(name: "Spilt Milk", neighborhood_id: 1)
Bar.create!(name: "Park and Field", neighborhood_id: 1)
Bar.create!(name: "Moonlighter", neighborhood_id: 1)
Bar.create!(name: "Best Intentions", neighborhood_id: 1)
Bar.create!(name: "Lost Lake", neighborhood_id: 1)
Bar.create!(name: "Northside Bar", neighborhood_id: 2)
Bar.create!(name: "Chop Shop", neighborhood_id: 2)
Bar.create!(name: "Bangers and Lace", neighborhood_id: 2)
Bar.create!(name: "Whiskey Business", neighborhood_id: 2)
Bar.create!(name: "Easy Bar", neighborhood_id: 2)

Special.create!(description: "well drinks half off", start_time: Time.new(2019, 1, 30, 4, 00), end_time: Time.new(2019, 1, 30, 6, 30), day_of_week: "wednesday", bar_id: 1)
Special.create!(description: "half off appetizers", start_time: Time.new(2019, 1, 30, 4, 30), end_time: Time.new(2019, 1, 30, 6, 00), day_of_week: "tuesday", bar_id: 1)
Special.create!(description: "draft beer and well drinks half off", start_time: Time.new(2019, 1, 30, 4, 00), end_time: Time.new(2019, 1, 30, 6, 00), day_of_week: "thursday", bar_id: 1)
Special.create!(description: "free shot with a domestic beer", start_time: Time.new(2019, 1, 30, 4, 00), end_time: Time.new(2019, 1, 30, 6, 30), day_of_week: "wednesday", bar_id: 1)
Special.create!(description: "$2 select beers", start_time: Time.new(2019, 1, 30, 5, 00), end_time: Time.new(2019, 1, 30, 7, 00), day_of_week: "thursday", bar_id: 1)
Special.create!(description: "half off whiskey and scotches", start_time: Time.new(2019, 1, 30, 5, 00), end_time: Time.new(2019, 1, 30, 9, 00), day_of_week: "thursday", bar_id: 2)
Special.create!(description: "half off everything", start_time: Time.new(2019, 1, 30, 5, 00), end_time: Time.new(2019, 1, 30, 7, 00), day_of_week: "friday", bar_id: 2)
Special.create!(description: "half off wine bottles and $1 oysters", start_time: Time.new(2019, 1, 30, 4, 00), end_time: Time.new(2019, 1, 30, 6, 00), day_of_week: "wednesday", bar_id: 3)
Special.create!(description: "half off glasses of wine and appetizers", start_time: Time.new(2019, 1, 30, 4, 00), end_time: Time.new(2019, 1, 30, 6, 00), day_of_week: "monday", bar_id: 4)
Special.create!(description: "half off appetizers", start_time: Time.new(2019, 1, 30, 4, 00), end_time: Time.new(2019, 1, 30, 6, 00), day_of_week: "tuesday", bar_id: 5)

Comment.create!(details: "bar was great", user_id: 1, bar_id: 1)
Comment.create!(details: "servers were nice but a little pricey", user_id: 1, bar_id: 1)
Comment.create!(details: "very clean bar and comfortable bar stools", user_id: 1, bar_id: 1)
